# Generated by Django 5.1.2 on 2025-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
